// Tất cả tham chiếu tới phần tử DOM dùng chung trong game
export const elements = {
  userClicks: document.getElementById("user-clicks"),
  userBucks: document.getElementById("user-bucks"),
  userMult: document.getElementById("user-mult"),
  userCps: document.getElementById("user-cps"),
  userLevel: document.getElementById("user-level"),
  nextLevelReward: document.getElementById("next-level-reward"),
  xp: document.getElementById("xp"),
  neededXp: document.getElementById("needed-xp"),
  xpBar: document.getElementById("xp-bar"),
  xpPercentage: document.getElementById("xp-percentage"),
  clickButton: document.getElementById("click-button"),
  upgradesList: document.getElementById("upgrades-list"),
  achievementsList: document.getElementById("achievements-list"),
  settingsModal: document.getElementById("settings-modal"),
  settingsContent: document.querySelector("#settings-modal > div"),
  openSettings: document.getElementById("open-settings"),
  closeSettings: document.getElementById("close-settings"),
  saveGame: document.getElementById("save-game"),
  resetGame: document.getElementById("reset-game"),
  toggleUpgrades: document.getElementById("toggle-upgrades"),
  darkModeToggle: document.getElementById("dark-mode-toggle"),
  sfxToggle: document.getElementById("sfx-toggle"),
  // --- Prestige / Gems ---
  userGems: document.getElementById("user-gems"),
  prestigePotential: document.getElementById("prestige-potential"),
  prestigeCount: document.getElementById("prestige-count"),
  prestigeButton: document.getElementById("prestige-button"),
  gemShopList: document.getElementById("gem-shop-list"),
  critShopList: document.getElementById("crit-shop-list"),
  critChanceDisplay: document.getElementById("crit-chance-display"),
  critDamageDisplay: document.getElementById("crit-damage-display"),
  // --- Combo / Golden Gift buff ---
  comboIndicator: document.getElementById("combo-indicator"),
  goldenBuffIndicator: document.getElementById("golden-buff-indicator"),
  // --- Offline Earnings ---
  offlineEarningsModal: document.getElementById("offline-earnings-modal"),
  offlineDuration: document.getElementById("offline-duration"),
  offlineEarningsAmount: document.getElementById("offline-earnings-amount"),
  offlineEarningsClose: document.getElementById("offline-earnings-close"),
  // --- Thăng Thiên / Cây Kỹ Năng / Bộ Sưu Tập ---
  openSkillTree: document.getElementById("open-skilltree"),
  skillTreeModal: document.getElementById("skilltree-modal"),
  closeSkillTree: document.getElementById("close-skilltree"),
  userCrystals: document.getElementById("user-crystals"),
  ascensionStatus: document.getElementById("ascension-status"),
  ascendButton: document.getElementById("ascend-button"),
  tabSkillTree: document.getElementById("tab-skilltree"),
  tabCollection: document.getElementById("tab-collection"),
  skillTreePanel: document.getElementById("skilltree-panel"),
  collectionPanel: document.getElementById("collection-panel"),
  powerBranchList: document.getElementById("power-branch-list"),
  speedBranchList: document.getElementById("speed-branch-list"),
  critBranchList: document.getElementById("crit-branch-list"),
  ascensionBranchList: document.getElementById("ascension-branch-list"),
  collectionProgress: document.getElementById("collection-progress"),
  collectionList: document.getElementById("collection-list"),
  tabQuests: document.getElementById("tab-quests"),
  tabStats: document.getElementById("tab-stats"),
  tabWorlds: document.getElementById("tab-worlds"),
  tabNirvana: document.getElementById("tab-nirvana"),
  questsPanel: document.getElementById("quests-panel"),
  statsPanel: document.getElementById("stats-panel"),
  worldsPanel: document.getElementById("worlds-panel"),
  nirvanaPanel: document.getElementById("nirvana-panel"),
  questsList: document.getElementById("quests-list"),
  weeklyQuestsList: document.getElementById("weekly-quests-list"),
  statsList: document.getElementById("stats-list"),
  worldsList: document.getElementById("worlds-list"),
  // --- Niết Bàn ---
  userXaLoi: document.getElementById("user-xa-loi"),
  nirvanaStatus: document.getElementById("nirvana-status"),
  nirvanaButton: document.getElementById("nirvana-button"),
  eternalMultLevel: document.getElementById("eternal-mult-level"),
  eternalMultBonus: document.getElementById("eternal-mult-bonus"),
  eternalMultCost: document.getElementById("eternal-mult-cost"),
  eternalMultButton: document.getElementById("eternal-mult-button"),
  gachaCost: document.getElementById("gacha-cost"),
  gachaButton: document.getElementById("gacha-button"),
  divineBeastsList: document.getElementById("divine-beasts-list"),
  // --- Chấm thông báo (badges) ---
  badgeSkillTree: document.getElementById("badge-skilltree"),
  badgeQuests: document.getElementById("badge-quests"),
  badgeWorlds: document.getElementById("badge-worlds"),
  badgeNirvana: document.getElementById("badge-nirvana"),
  badgeSkillTreeFloating: document.getElementById("badge-skilltree-floating"),
  // --- Boss Click ---
  bossBar: document.getElementById("boss-bar"),
  bossName: document.getElementById("boss-name"),
  bossHpBar: document.getElementById("boss-hp-bar"),
  bossHpText: document.getElementById("boss-hp-text"),
  bossTimerText: document.getElementById("boss-timer-text"),
};
